### ISSUE TITLE
Investigation of under_scores in keywords (m_var)

### ISSUE THREAD

**Issue by noah4546** [BCHRobotics/Trojans2024#12]
- Investigate what the official java standards are for this usage.
- Investigate the standards that came from REV

Please link supporting documents to this issue.

**Comment by Stevon2386** [comment]
WPILib and REV both use Hungarian notation because its a [C++ standard](https://www.webkit.org/code-style-guidelines/#names-data-members), and they want to keep their Java and C++ code as similar as possible. It is not necessary for us to use this notation, it is not part of [Java standards](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf).

**Comment by noah4546** [comment]
Will stay with current naming for now, may open this ticket again in the future.
